### ISSUE TITLE
Homepage Creation

### ISSUE THREAD

**Issue by hunterls97** [6ixside/gifter#3]
Take a look at the mockup that Akshay posted in the google drive (should be a link in the slack group)

lets make the hompage with a top bar component, 2 buttons for the navigation (labeled gift and trade) and a region at the bottom to list the users gift card inventory. (see meeting july 8/initial design.jpg in google drive)

please use material 2 components where applicable 
https://material.angular.io/

**Comment by connordear** [comment]
Is it okay to use a tab system for now? While I was making it I thought a tab system would actually be pretty suitable here:

![36967427_10155463242087751_2518893058045509632_n](https://user-images.githubusercontent.com/18018265/42638469-b8af84c4-85bb-11e8-9a13-438cae23b457.png)

**Comment by hunterls97** [comment]
Yeah tab system looks good! I think that solves some of our layout issues.

**Comment by connordear** [comment]
Beauty, the layout should be all there by tonight. I don't have any real infrastructure worked into it at this point, but that will depend a lot on user account logic - I guess that's in #6 ? I could start working on that next

**Comment by hunterls97** [comment]
yeah sounds good, i'll assign it to you
